jarsigner disable fix

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -22,8 +22,6 @@ jobs:
   build-amd64:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    needs:
-      - jarsigner
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -78,7 +76,6 @@ jobs:
     runs-on: ubuntu-latest
     # needs amd64 build because version number - arm image is not runable with buildx
     needs:
-      - jarsigner
       - build-amd64
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -97,6 +94,7 @@ jobs:
           ARCH: ARM
         run: |
           echo "Buildx supported platforms: ${{ steps.buildx.outputs.platforms }}"
+          cp -f checksum.signed files || { echo "Checksum file not found"; exit 1; }
           docker build --rm --platform linux/arm64 -t croc/unimus-core-arm64 . || { echo "docker image build failed - arm64"; exit 1; }
           docker tag croc/unimus-core-arm64 croc/unimus-core-arm64
           docker tag croc/unimus-core-arm64 quay.io/croc/unimus-core-arm64
